GestionInventarioAC/GestionInventarioAC/Controllers/ClientesController.cs
using Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Entities;
using Helper;
using Services.Interfaces;

namespace Controllers;

public class ClientesController : Controller
{
    private readonly IClientesRepository _clientesRepository;
    private readonly IMapper _mapper;

    public ClientesController(IClientesRepository categoryRepository, IMapper mapper)
    {
        _clientesRepository = categoryRepository ??
            throw new ArgumentNullException(nameof(categoryRepository));
        ;
        _mapper = mapper ??
            throw new ArgumentNullException(nameof(mapper))
        ;
    }

    [HttpGet]
    public async Task<ActionResult> Index()
    {
        var categories = await _clientesRepository.ListClientesAsync();
        var categoriesDto = _mapper.Map<ClientesDto>(categories);

        return View(categoriesDto);
    }

    [HttpGet]
    public async Task<ActionResult> Agregar()
    {
        var category = new ClienteDto();
        return View("Grabar", category);
    }

    [HttpGet]
    public async Task<ActionResult> Editar(int id)
    {
        var categorie = await _clientesRepository.GetCliente(id);

        if (categorie == null) categorie = new Cliente();

        var categorieDto = _mapper.Map<ClienteDto>(categorie);
        categorieDto.TipoManto = Constants.Modificar;

        return View("Grabar", categorieDto);
    }

    [HttpGet]
    public async Task<ActionResult> Eliminar(int id)
    {
        var categorie = await _clientesRepository.GetCliente(id);
        var categorieDto = _mapper.Map<ClienteDto>(categorie);
        categorieDto.TipoManto = Constants.Eliminar;

        return View("Grabar", categorieDto);
    }

    [HttpPost]
    public async Task<ActionResult> Grabar(ClienteDto model, String button)
    {
        if (button == "Salir") return RedirectToAction("Index");

        if (!ModelState.IsValid && model.TipoManto != Constants.Eliminar) return View("Grabar", model);

        var categorie = _mapper.Map<Cliente>(model);

        switch (model.TipoManto)
        {
            case Constants.Agregar: _clientesRepository.AddCliente(categorie); break;
            case Constants.Modificar: _clientesRepository.UpdateCliente(categorie); break;
            case Constants.Eliminar: _clientesRepository.RemoveCliente(categorie); break;
        }

        await _clientesRepository.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }
}

GestionInventarioAC/GestionInventarioAC/Controllers/ComprasController.cs
using Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Entities;
using Helper;
using Services.Interfaces;

namespace Controllers;

public class ComprasController : Controller
{
	private readonly IComprasRepository _comprasRepository;
    private readonly IMapper _mapper;

    public ComprasController(IComprasRepository comprasRepository, IMapper mapper)
	{
        _comprasRepository = comprasRepository ??
			throw new ArgumentNullException(nameof(comprasRepository));
        ;
        _mapper = mapper ??
            throw new ArgumentNullException(nameof(mapper))
		;
    }

    [HttpGet]
	public async Task<ActionResult> Index()
	{
		var categories = await _comprasRepository.ListComprasAsync();
        var categoriesDto = _mapper.Map<ComprasDto>(categories);

        return View(categoriesDto);
	}

	[HttpGet]
	public async Task<ActionResult> Agregar()
	{
		var category = new CompraDto();
		category.Proveedores = await _comprasRepository.ComboProveedoresAsync();

		return View("Grabar", category);
	}

	[HttpGet]
	public async Task<ActionResult> Editar(int id)
    {
		var categorie = await _comprasRepository.GetCompra(id);

		if(categorie == null) categorie = new Compra();

        var categorieDto = _mapper.Map<CompraDto>(categorie);
        categorieDto.Proveedores = await _comprasRepository.ComboProveedoresAsync();
        categorieDto.TipoManto = Constants.Modificar;

		return View("Grabar", categorieDto);
    }

    [HttpGet]
	public async Task<ActionResult> Eliminar(int id)
    {
		var categorie = await _comprasRepository.GetCompra(id);
		var categorieDto = _mapper.Map<CompraDto>(categorie);
        categorieDto.Proveedores = await _comprasRepository.ComboProveedoresAsync();
        categorieDto.TipoManto = Constants.Eliminar;

		return View("Grabar", categorieDto);
    }

	[HttpPost]
	public async Task<ActionResult> Grabar(CompraDto model, String button)
	{
		if (button == "Salir") return RedirectToAction("Index");

        if (!ModelState.IsValid && model.TipoManto != Constants.Eliminar)
		{
            model.Proveedores = await _comprasRepository.ComboProveedoresAsync();
            return View("Grabar", model);
        }
		
		var categorie = _mapper.Map<Compra>(model);

		switch (model.TipoManto)
        {
			case Constants.Agregar: _comprasRepository.AddCompra(categorie); break;
			case Constants.Modificar: _comprasRepository.UpdateCompra(categorie); break;
			case Constants.Eliminar: _comprasRepository.RemoveCompra(categorie); break;
        }

		await _comprasRepository.SaveChangesAsync();

		return RedirectToAction(nameof(Index));
    }
}

GestionInventarioAC/GestionInventarioAC/Controllers/ProductsController.cs
using Services.Interfaces;
using Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Entities;
using Helper;

namespace Controllers;

public class ProductsController : Controller
{
	private readonly IProductsRepository _productRepository;
    private readonly IMapper _mapper;

    public ProductsController(IProductsRepository productRepository, IMapper mapper)
	{
        _productRepository = productRepository ??
			throw new ArgumentNullException(nameof(productRepository));
        ;
        _mapper = mapper ??
            throw new ArgumentNullException(nameof(mapper))
		;
    }

    [HttpGet]
	public async Task<ActionResult> Index()
	{
		var products = await _productRepository.ListProductsAsync();
        var productsDto = _mapper.Map<ProductosDto>(products);

        return View(productsDto);
	}

	[HttpGet]
	public async Task<ActionResult> Agregar()
	{
		var productDto = new ProductoDto();
		productDto.Categories = await _productRepository.ComboCategoriesAsync();

		return View("Grabar", productDto);
	}

	[HttpGet]
	public async Task<ActionResult> Editar(int id)
    {
		var product = await _productRepository.GetProductAsync(id);

		if(product == null) product = new Producto();

        var productDto = _mapper.Map<ProductoDto>(product);
        productDto.Categories = await _productRepository.ComboCategoriesAsync();
        productDto.tipoManto = Constants.Modificar;

		return View("Grabar", productDto);
    }

    [HttpGet]
	public async Task<ActionResult> Eliminar(int id)
    {
		var product = await _productRepository.GetProductAsync(id);
		var productDto = _mapper.Map<ProductoDto>(product);

        productDto.Categories = await _productRepository.ComboCategoriesAsync();
        productDto.tipoManto = Constants.Eliminar;

		return View("Grabar", productDto);
    }

	[HttpPost]
	public async Task<ActionResult> Grabar(ProductoDto model, String button)
	{
		if (button == "Salir") return RedirectToAction("Index");

        if (!ModelState.IsValid && model.tipoManto != Constants.Eliminar)
		{
            model.Categories = await _productRepository.ComboCategoriesAsync();
            return View("Grabar", model);
        }

		var product = _mapper.Map<Producto>(model);

		switch (model.tipoManto)
        {
			case Constants.Agregar:   _productRepository.AddProduct(product); break;
			case Constants.Modificar: _productRepository.UpdateProduct(product); break;
			case Constants.Eliminar:  _productRepository.DeleteProduct(product); break;
        }

		await _productRepository.SaveChangesAsync();

		return RedirectToAction(nameof(Index));
    }
}

GestionInventarioAC/GestionInventarioAC/Controllers/VentasController.cs
using Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Entities;
using Helper;
using Services.Interfaces;
using Services;

namespace Controllers;

public class VentasController : Controller
{
	private readonly IVentasRepository _ventasRepository;
    private readonly IMapper _mapper;

    public VentasController(IVentasRepository categoryRepository, IMapper mapper)
	{
        _ventasRepository = categoryRepository ??
			throw new ArgumentNullException(nameof(categoryRepository));
        ;
        _mapper = mapper ??
            throw new ArgumentNullException(nameof(mapper))
		;
    }

    [HttpGet]
	public async Task<ActionResult> Index()
	{
		var categories = await _ventasRepository.ListVentasAsync();
        var categoriesDto = _mapper.Map<VentasDto>(categories);

        return View(categoriesDto);
	}

	[HttpGet]
	public async Task<ActionResult> Agregar()
	{
		var category = new VentaDto();
        category.Clientes = await _ventasRepository.ComboClientesAsync();

        return View("Grabar", category);
	}

	[HttpGet]
	public async Task<ActionResult> Editar(int id)
    {
		var categorie = await _ventasRepository.GetVenta(id);

		if(categorie == null) categorie = new Venta();

        var categorieDto = _mapper.Map<VentaDto>(categorie);
        categorieDto.Clientes = await _ventasRepository.ComboClientesAsync();
        categorieDto.TipoManto = Constants.Modificar;

		return View("Grabar", categorieDto);
    }

    [HttpGet]
	public async Task<ActionResult> Eliminar(int id)
    {
		var categorie = await _ventasRepository.GetVenta(id);
		var categorieDto = _mapper.Map<VentaDto>(categorie);

        categorieDto.Clientes = await _ventasRepository.ComboClientesAsync();
        categorieDto.TipoManto = Constants.Eliminar;

		return View("Grabar", categorieDto);
    }

	[HttpPost]
	public async Task<ActionResult> Grabar(VentaDto model, String button)
	{
		if (button == "Salir") return RedirectToAction("Index");

        if (!ModelState.IsValid && model.TipoManto != Constants.Eliminar)
		{
            model.Clientes = await _ventasRepository.ComboClientesAsync();
            return View("Grabar", model);
        }
		
		var categorie = _mapper.Map<Venta>(model);

		switch (model.TipoManto)
		{
			case Constants.Agregar: _ventasRepository.AddVenta(categorie); break;
			case Constants.Modificar: _ventasRepository.UpdateVenta(categorie); break;
			case Constants.Eliminar: _ventasRepository.RemoveVenta(categorie); break;
		}

		await _ventasRepository.SaveChangesAsync();

		return RedirectToAction(nameof(Index));
    }
}

GestionInventarioAC/GestionInventarioAC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GestionInventarioAC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/GestionInventarioAC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestionInventarioAC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
           
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventories" asp-action="Index">Inventario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proveedores" asp-action="Index">Proveedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
                        </li>
                    </ul>
                </div>
        
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>